# Generated by Django 4.0.1 on 2022-08-05 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import integrations.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dash and underscore characters are accepted', regex='^[a-zA-Z0-9\\-_]+$')])),
                ('type', models.CharField(max_length=64)),
                ('is_enabled', models.BooleanField(default=True)),
                ('has_report', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=integrations.utils.get_default_configuration)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opencve_integrations',
            },
        ),
    ]
