# Generated by Django 4.1 on 2023-04-23 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Special characters (except dash and underscore) are not accepted",
                                regex="^[a-zA-Z0-9\\-_ ]+$",
                            )
                        ],
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("is_enabled", models.BooleanField(default=True)),
                ("has_report", models.BooleanField(default=False)),
                (
                    "configuration",
                    models.JSONField(default=projects.utils.get_default_configuration),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_integrations",
            },
        ),
    ]
