# Generated by Django 4.2.1 on 2023-05-20 08:19

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_name_alter_project_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="subscriptions",
            field=models.JSONField(default=projects.models.get_default_subscriptions),
        ),
    ]
