# Generated by Django 4.1 on 2023-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0002_remove_change_task_change_commit_change_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="path",
            field=models.TextField(default=None),
        ),
    ]
