# Generated by Django 4.1 on 2023-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("changes", "0004_alter_change_commit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="change",
            name="json",
        ),
    ]
