# Generated by Django 4.1 on 2023-03-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0005_remove_change_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="is_reviewed",
        ),
    ]
