# Generated by Django 4.1 on 2023-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0006_remove_event_is_reviewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_cve", "New CVE"),
                    ("first_time", "Vendor(s)/Product(s) appeared for the first time"),
                    ("references", "Reference(s) changed"),
                    ("cpes", "CPE(s) changed"),
                    ("cvss", "CVSS changed"),
                    ("summary", "Summary changed"),
                    ("cwes", "CWE(s) changed"),
                ],
                default="new_cve",
                max_length=10,
            ),
        ),
    ]
