# Generated by Django 4.2.1 on 2023-05-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_project_subscriptions"),
        ("changes", "0008_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="user",
        ),
        migrations.AddField(
            model_name="report",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
