# Generated by Django 4.0.1 on 2022-03-14 19:03

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.CreateModel(
            name="Cve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("cve_id", models.CharField(max_length=20, unique=True)),
                ("json", models.JSONField()),
                ("vendors", models.JSONField()),
                ("cwes", models.JSONField()),
                ("summary", models.TextField()),
                ("cvss2", models.FloatField(default=None, null=True)),
                ("cvss3", models.FloatField(default=None, null=True)),
            ],
            options={
                "db_table": "opencve_cves",
            },
        ),
        migrations.CreateModel(
            name="Cwe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("cwe_id", models.CharField(db_index=True, max_length=16)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "opencve_cwes",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=256, unique=True)),
            ],
            options={
                "db_table": "opencve_vendors",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "opencve_products",
            },
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vendors"], name="ix_cves_vendors"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cwes"], name="ix_cves_cwes"
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("summary"),
                    name="gin_trgm_ops",
                ),
                name="ix_cves_summary",
            ),
        ),
        migrations.AddIndex(
            model_name="cve",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper("cve_id"), name="gin_trgm_ops"
                ),
                name="ix_cves_cve_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "vendor_id"), name="ix_unique_products"
            ),
        ),
    ]
