# Generated by Django 4.1 on 2023-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cve_sources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cve",
            name="json",
        ),
        migrations.AlterField(
            model_name="cve",
            name="cwes",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="cve",
            name="summary",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="cve",
            name="vendors",
            field=models.JSONField(default=[]),
        ),
    ]
