# Generated by Django 4.1 on 2022-10-19 21:19

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advisory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("key", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=128)),
                ("text", models.TextField(default=None)),
                ("source", models.CharField(max_length=32)),
                ("extras", models.JSONField()),
                ("original_url", models.URLField()),
            ],
            options={
                "db_table": "opencve_advisories",
            },
        ),
    ]
