# Generated by Django 4.1 on 2022-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
