# Generated by Django 4.1 on 2022-09-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="text",
            field=models.TextField(default=None),
        ),
    ]
